title: Navegador de Acervos

# for local dev:
#   jekyll s --baseurl=
baseurl: /acervos-interface

exclude: [
  .git,
  .gitignore,
  Gemfile,
  Gemfile.lock,
  README.md,
  .sass-cache/,
  .jekyll-cache/,
  gemfiles/,
  node_modules/
]

markdown: kramdown
port: 8421
